# Generated by Django 2.1.3 on 2018-11-17 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovingAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('FAD', 'Faculty Advisor'), ('GHW', 'Warden - Girls Hostel'), ('BHW', 'Warden - Boys Hostel'), ('SUP', 'Supervisor'), ('OTH', 'Other')], default='FAD', max_length=3)),
                ('designation', models.CharField(choices=[('ASIP', 'Assistant Professor'), ('ASOP', 'Associate Professor'), ('PROF', 'Professor'), ('OTH', 'Other')], default='OTH', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10)),
                ('year_of_joining', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('program', models.CharField(choices=[('BTC', 'Bachelor of Technology'), ('MTC', 'Master of Technology'), ('MSC', 'Master of Science'), ('PHD', 'Doctorate of Philosophy'), ('OTH', 'Other')], default='BTC', max_length=5)),
                ('discipline', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('CEE', 'Civil and Environmental Engineering'), ('CBE', 'Chemical and Biochemical Engineering'), ('ME', 'Mechanical Engineering'), ('MME', 'Metallurgical and Materials Engineering'), ('MSE', 'Material Science and Engineering'), ('CHEM', 'Chemistry'), ('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('HSS', 'Humanities and Social Sciences'), ('MNC', 'Mathematics and Computing'), ('MT', 'Mechatronics'), ('NT', 'Nanoscience and Technology'), ('CM', 'Communication System engineering'), ('OTH', 'Other')], default='CSE', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('hostel', models.CharField(choices=[('GH', 'Girls Hostel'), ('BH', 'Boys Hostel')], default='BH', max_length=2)),
                ('block', models.CharField(max_length=1)),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('AA', 'Authority')], default='S', max_length=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.UserAccount'),
        ),
        migrations.AddField(
            model_name='approvingauthority',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authority', to='users.UserAccount'),
        ),
    ]
