# Generated by Django 2.1.3 on 2018-11-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181117_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_joining',
            field=models.IntegerField(default=0),
        ),
    ]
