# Generated by Django 2.1.3 on 2018-11-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_status', models.CharField(choices=[('PEN', 'Pending'), ('APP', 'Approved'), ('REJ', 'Rejected')], default=('PEN', 'Pending'), max_length=10)),
                ('reason_for_leave', models.CharField(max_length=200)),
                ('going_to_type', models.CharField(choices=[('NAT', 'Native'), ('OTH', 'Other')], default='NAT', max_length=3)),
                ('going_to_place', models.CharField(max_length=50)),
                ('date_of_leaving', models.DateField(null=True)),
                ('date_of_returning', models.DateField(null=True)),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ApprovingAuthority')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
    ]
