# Generated by Django 2.1.3 on 2018-11-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('APP', 'Approved'), ('REJ', 'Rejected')], default='PEN', max_length=10),
        ),
    ]
