# Generated by Django 2.1.3 on 2018-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181117_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_of_leaving',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_of_returning',
            field=models.DateTimeField(null=True),
        ),
    ]
