# Generated by Django 2.1.3 on 2018-11-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181117_1010'),
        ('app', '0003_auto_20181117_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovingFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('program', models.CharField(choices=[('BTC', 'Bachelor of Technology'), ('MTC', 'Master of Technology'), ('MSC', 'Master of Science'), ('PHD', 'Doctorate of Philosophy'), ('OTH', 'Other')], default='BTC', max_length=5)),
                ('discipline', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('CEE', 'Civil and Environmental Engineering'), ('CBE', 'Chemical and Biochemical Engineering'), ('ME', 'Mechanical Engineering'), ('MME', 'Metallurgical and Materials Engineering'), ('MSE', 'Material Science and Engineering'), ('CHEM', 'Chemistry'), ('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('HSS', 'Humanities and Social Sciences'), ('MNC', 'Mathematics and Computing'), ('MT', 'Mechatronics'), ('NT', 'Nanoscience and Technology'), ('CM', 'Communication System engineering'), ('OTH', 'Other')], default='CSE', max_length=50)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ApprovingAuthority')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApprovingWarden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('hostel', models.CharField(choices=[('GH', 'Girls Hostel'), ('BH', 'Boys Hostel')], default='BH', max_length=2)),
                ('warden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ApprovingAuthority')),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('APPF', 'Approved by Faculty'), ('APPW', 'Approved by Warden'), ('REJ', 'Rejected')], default='PEN', max_length=10),
        ),
    ]
