# Generated by Django 2.1.3 on 2018-11-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181118_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapprovingfaculty',
            old_name='faculty',
            new_name='authority',
        ),
        migrations.RenameField(
            model_name='leaveapprovingwarden',
            old_name='warden',
            new_name='authority',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='authority',
        ),
        migrations.AddField(
            model_name='leave',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LeaveApprovingFaculty'),
        ),
        migrations.AddField(
            model_name='leave',
            name='warden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LeaveApprovingWarden'),
        ),
    ]
