# Generated by Django 2.1.3 on 2018-11-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181118_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='warden',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LeaveApprovingWarden'),
        ),
        migrations.AlterField(
            model_name='leaveapprovingfaculty',
            name='authority',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='users.ApprovingAuthority'),
        ),
        migrations.AlterField(
            model_name='leaveapprovingwarden',
            name='authority',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warden', to='users.ApprovingAuthority'),
        ),
    ]
